### ISSUE TITLE
Typo'ed package layout for envoy.extensions.filter

### ISSUE THREAD

**Issue by htuch** [envoyproxy/envoy#10809]
The regular directory/package structure is `envoy.extensions.filters`, yet we have one filter in `envoy.extension.filter`, see https://github.com/envoyproxy/envoy/tree/master/api/envoy/extensions/filter/udp/dns_filter/v3alpha.

Since this is v3alpha, I think we should just move it to the `envoy.extensions.filters` tree as a breaking change.

@envoyproxy/api-shepherds @abaptiste

**Comment by htuch** [comment]
We could also put in place a regression test in `check_format` to look for specifically this pattern, as I think it's an easy typo to hit that is hard to pickup in review.

**Comment by mattklein123** [comment]
+1 please just move it. @abaptiste do you mind taking this?

**Comment by htuch** [comment]
This was fixed in https://github.com/envoyproxy/envoy/pull/10697

**Comment by abaptiste** [comment]
Sorry gents :(  Just seeing this.  Still getting the hang of this github thing.
