### ISSUE TITLE
OSS fuzz issue 43725 & 43729: Wasm-filter does not initialize

### ISSUE THREAD

**Issue by vehre-x41** [envoyproxy/envoy#21432]
*Title: OSS fuzz issue 43725 & 43729: Wasm-filter does not initialize*

*Description:*
In both issues 43725 and 43729 filter_fuzz_test tries to configure a wasm-http-filter. In both issues [tls_slot_->get()](https://github.com/envoyproxy/envoy/blob/a477786206a5087fdca82d5af9ce3f852dfdc9a3/source/extensions/filters/http/wasm/wasm_filter.h#L31) triggers an assert, because the tls_slot_ is not initialized. I tried a decent time to figure how to initialize this correctly, but never got any better. Therefore the questions:

1. What am I missing here?
2. Is the wasm-filter intended to be initialized standalone at all?
3. Where does the wasm-implementation get its dataprovider from, that would trigger the callback generated [here](https://github.com/envoyproxy/envoy/blob/a477786206a5087fdca82d5af9ce3f852dfdc9a3/source/extensions/filters/http/wasm/wasm_filter.cc#L17)? With the configurations given by the testcases, the callback provided to wasm-implementation never gets triggered.
4. Should the wasm-filter probably be excluded from general filter_fuzz_test?

*Relevant Links:*
[OSS Fuzz 43725](https://oss-fuzz.com/testcase-detail/6314611891109888)
[OSS Fuzz 43729](https://oss-fuzz.com/testcase-detail/5144065983774720)

**Comment by vehre-x41** [comment]
CC @adisuissa @KBaichoo @pradeepcrao @htuch

**Comment by PiotrSikora** [comment]
Does it try to load invalid Wasm module from remote endpoint? If that's the case, then this might be fixed in #20843.

**Comment by vehre-x41** [comment]
Well, I don't think so. One of the configurations is:
```
config {
  name: "envoy.filters.http.wasm"
  typed_config {
    type_url: "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"
    value: "\nM\0329\n\001]\022\001]\032/\022-\n&\n\037envoy.filters.http.health_check\022\001\014\032\000\022\0014\032\000(\0012\020\n\006\n\002>c\022\000\n\006\n\002E]\022\000"
  }
  is_optional: true
}
```
where the `typed_config` expands to:
```
typed_config {
  [type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm] {
    config {
      vm_config {
        vm_id: "]"
        runtime: "]"
        code {
          remote {
            http_uri {
              uri: "envoy.filters.http.health_check"
              cluster: "\014"
              timeout {
              }
            }
            sha256: "4"
            retry_policy {
            }
          }
        }
        allow_precompiled: true
      }
      capability_restriction_config {
        allowed_capabilities {
          key: ">c"
          value {
          }
        }
        allowed_capabilities {
          key: "E]"
          value {
          }
        }
      }
    }
  }
}
is_optional: true
```
Note, that this is fuzzer input, i.e., the fuzzer not necessary construct a config that makes sense.

**Comment by PiotrSikora** [comment]
Yeah, that matches my description (remote fetch):
```
        code {
          remote {
            http_uri {
```
it should be addressed by https://github.com/envoyproxy/envoy/pull/20843.

**Comment by vehre-x41** [comment]
I have tested with df49d91459e0ed550f9815b4d85c2420b5ddde6e but it still crashes. The config used is the one from [this](https://github.com/envoyproxy/envoy/issues/21432#issuecomment-1139370260) comment.

Therefore no, it is not addressed by #20843.
