### ISSUE TITLE
Envoy debug docker images do not contain debug symbols from v1.26.0

### ISSUE THREAD

**Issue by jparklab** [envoyproxy/envoy#28100]
*Title*: *Envoy debug docker images do not contain debug symbols from v1.26.0*

*Description*:

Official envoy docker images with tags that have 'debug-' prefix do not have debug symbols from v1.26.0. 
e.g. the image sizes of debug-v1.26.0 and v1.26.0 are the same(https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=v1.26.0)

```
$ nm envoy
en: envoy: no symbols
```

*Repro steps*:

```
$ version=v1.26.0
$ docker pull envoyproxy/envoy:debug-${version}
$ containerID=$(docker create envoyproxy/envoy:debug-${version})
$ docker cp ${containerID):/usr/local/bin/envoy .
$ nm envoy
```

**Comment by phlax** [comment]
thanks for raising this @jparklab - i will take a look and see if i can see why this is happening

**Comment by phlax** [comment]
confirming that all 1.26 debug images are incorrect - including dev images - which kinda makes things easier as its not release specific

**Comment by phlax** [comment]
@jparklab afaict this is now fixed (not yet for releases tho)

```console
$ docker run -ti --rm envoyproxy/envoy:debug-dev ls /usr/local/bin -lh
total 834M
-rwxr-xr-x 1 root root 469M Jan  1  2000 envoy
-rwxr-xr-x 1 root root 366M Jan  1  2000 envoy.dwp
-rwxr-xr-x 1 root root  19K Jan  1  2000 su-exec
```

thanks again for the report

**Comment by jparklab** [comment]
@phlax Thanks for fixing this quickly. I see docker images on the official repo is still the same (https://hub.docker.com/r/envoyproxy/envoy/tags?page=1&name=v1.26.0). Will this fix be back-ported to the docker images, or will only be applied to new docker images?

**Comment by phlax** [comment]
>  Will this fix be back-ported to the docker images, or will only be applied to new docker images?

it has already been backported to the 1.26 branch and will be included in the next patch release - the existing images wont change
