### ISSUE TITLE
SocketOptionImpl::setIpSocketOption is broken with mock socket

### ISSUE THREAD

**Issue by akonradi** [envoyproxy/envoy#3232]
SocketOptionImpl::setIpSocketOption calls `Address::addressFromFd` with the file descriptor obtained from the socket. `Address::addressFromFd` makes system calls to get information from the file descriptor. If the `Socket` passed to `setIpSocketOption` is a mock object, its file descriptor is meaningless, so making system calls with the file descriptor is a bad idea. Instead, the socket should have a method to return an `Address::InstanceConstSharedPtr` that can be overriden in mocks and that performs the appropriate system calls in the real implementation.

[*Relevant Links*:]
https://github.com/envoyproxy/envoy/blob/55a95f481798a571ef00e02d056fe6b180de8876/source/common/network/socket_option_impl.cc#L58
https://github.com/envoyproxy/envoy/blob/1db0c7ace77263c554d18dfffa21ea2b5ea6f3b9/source/common/network/address_impl.cc#L63

**Comment by mattklein123** [comment]
Fixed.

**Comment by akonradi** [comment]
Not fixed. This is a bigger issue about how `SocketOptionImpl` requests information from a `Socket` object, namely that it breaks encapsulation.
